# Generated by Django 4.2.6 on 2023-10-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted'), (2, 'In Active')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted'), (2, 'In Active')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('objective', models.CharField(max_length=1000)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.experience')),
                ('user_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.userextra')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
