# Generated by Django 4.2.6 on 2023-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_alter_experience_description_alter_resume_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user_extra',
        ),
        migrations.AddField(
            model_name='resume',
            name='user_extra',
            field=models.ManyToManyField(to='user_manager.userextra'),
        ),
    ]
