# Generated by Django 4.2.6 on 2023-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_remove_resume_user_extra_resume_user_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(to='user_manager.experience'),
        ),
    ]
