# Generated by Django 4.2.6 on 2023-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_remove_resume_experience_resume_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
